#+TITLE: Lued Notes
#+AUTHOR: Calvin Beck
#+OPTIONS: ^:{}

* Introduction
  Lued is a debugger. The eventual goal is to embed lua and do some
  fanciness with it.

  The hope is to make this multiplatform in the future, but for now we
  are just going to meander through and make everything work on
  Linux. There are a lot of platform specific things which will need
  to be abstracted out in the future. It's not too bad, but I don't
  want to focus on that right away.

  We're not quite there yet.

* Mac OS X
  For now support for Mac OS X is to be left on the side. It seems
  that some things are different on the Apple side of things. For
  instance *ptrace* on apple is much different.

  [[http://uninformed.org/index.cgi?v=4&a=3&p=14][OS X ptrace info]]

  In the future this will hopefully be supported, but for now it's a
  bit of a headache to deal with multiple platforms.

* BSD Systems
  Currently we rely upon GNU make features for the Makefile. You will
  need to install gmake.

  The register structures on OpenBSD are different. We will have to
  abstract this in order to make everything work nicely.
